### ISSUE TITLE
Brak informacji o projekcie.

### ISSUE THREAD

**Issue by Memexurer** [ProgramistaZpolski/nowa-era-dk#2]
**po czo mi to?** czo to robi? moge robić pr'y?

**Comment by piotrbadelek** [comment]
to jest dekompilator do programów nowej ery więc możesz tam wsadzić jakąś płytę z podręcznika od informatyki i zdekompilować

**Comment by piotrbadelek** [comment]
moge juz zamknac czy jescze jakies pytania
